Create libiberty/libiberty.m4
Converting GDB to be a C++ program, I stumbled on 'basename' issues,
like:

 src/gdb/../include/ansidecl.h:169:64: error: new declaration ‘char* basename(const char*)’
 /usr/include/string.h:597:26: error: ambiguates old declaration ‘const char* basename(const char*)’

which I believe led to this bit in gold's configure.ac:

 dnl We have to check these in C, not C++, because autoconf generates
 dnl tests which have no type information, and current glibc provides
 dnl multiple declarations of functions like basename when compiling
 dnl with C++.
 AC_CHECK_DECLS([basename, ffs, asprintf, vasprintf, snprintf, vsnprintf, strverscmp])

These checks IIUC intend to generate all the HAVE_DECL_FOO symbols
that libiberty.h and ansidecl.h check.

GDB is missing these checks currently, which results in the conflict
shown above.

I could just copy gold's bits over to GDB.  But, since libiberty's
ansidecl.h and libiberty.h check HAVE_DECL_XXX symbols, ISTM that all
programs that use these headers should be doing the exact same
corresponding AC_CHECK_DECLS autoconf checks, and that there's good
potential for bit rot here.

So I thought of adding a m4 file that projects that use libiberty can
source to pull in the autoconf checks that libiberty needs done in
order to use its public headers.

Turns out that this has already happened.  Since I first wrote this a
few months back, libiberty gained more HAVE_DECL_FOO checks even, for
the strtol & friends replacements.

libiberty/ChangeLog:
2015-02-09  Pedro Alves  <palves@redhat.com>

	* libiberty.m4: New file.